# Generated by Django 4.2.5 on 2023-09-14 23:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_auto_20230914_2256'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoriesmodel',
            name='type',
            field=models.ForeignKey(limit_choices_to={'transaction_name__isnull': False}, null=True, on_delete=django.db.models.deletion.CASCADE, to='transactions.typesmodel'),
        ),
    ]
