# Generated by Django 4.2.5 on 2023-09-14 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_initial'),
    ]

    operations = [
    ]
