# Generated by Django 4.2.5 on 2023-09-14 22:03

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('transactions', '0002_initial'),
        ('users', '0002_initial'),
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportsModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('amount', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0, 'La cantidad no puede ser negativa.')])),
                ('information', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(6, 'La información debe tener al menos 6 caracteres.')])),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transactions.categoriesmodel', verbose_name='Categoría')),
                ('type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transactions.typesmodel', verbose_name='Tipo')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.usermodel', verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Reporte',
                'verbose_name_plural': 'Reportes',
            },
        ),
    ]
